name: remote_request
description: "A flutter package to request remote network calls i.e, Create , Read , Update , Delete, Patch, Put"
version: 0.0.2
homepage: https://github.com/GitFromGeeks/remote_request.git
repository: "https://github.com/GitFromGeeks/remote_request/tree/main/lib"
issue_tracker: "https://github.com/GitFromGeeks/remote_request"
documentation: "https://github.com/GitFromGeeks/remote_request/tree/main/lib"



environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


